apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-share
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-share
  resources:
    requests:
      storage: 20Gi
