apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        envFrom:
          - secretRef:
              name: postgres-secret
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: nfs
            mountPath: /var/lib/postgres/data
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:            
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432