apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        envFrom:
          - secretRef:
              name: postgres-secret
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: nfs-share
            mountPath: /var/lib/postgresql/data
            readOnly: false
      volumes:
      - name: nfs-share
        persistentVolumeClaim:
          claimName: nfs-share
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:            
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
